### ISSUE TITLE
Fix the documentation

### ISSUE THREAD

**Issue by gravitystorm** [cartocss/carto#3]
[cartocss.readthedocs.io/](https://cartocss.readthedocs.io/) currently is broken. We should publish the docs to readthedocs (automatically, if possible) and see if we can reclaim the same url.

**Comment by yvecai** [comment]
The doc is published again, Url ownership is apparently not a big issue at readthedocs.org !

 @gravitystorm  @pnorman  do you already have an account at https://readthedocs.org ? It would be good if an owner has maintainer role there.

**Comment by gravitystorm** [comment]
Yes - I'm `gravitystorm` at readthedocs. I got an invite but that is no longer working, so could you invite me again please?

**Comment by yvecai** [comment]
I revoked the invite because I wasn't certain it was the good gravitystorm. Done again.

**Comment by gravitystorm** [comment]
Docs are back online, so this issue can be closed.
